
import express from "express";
import dotenv from "dotenv";
import cron from "node-cron";
import { fetchLatestTechNews } from "./services/fetchNews.js";
import { generateTweetFromNews } from "./services/generateTweet.js";
import { postToTwitter } from "./services/postToTwitter.js";

dotenv.config();
const app = express();
let lastTweetTime = 0; // store last tweet timestamp
const MIN_INTERVAL = 60 * 1000; // 1 minute gap (change if needed)

app.get("/", (req, res) => {
  res.send("🤖 AI Tweet Bot is running!");
});


app.get("/tweet", async (req, res) => {


  const now = Date.now();

  if (now - lastTweetTime < MIN_INTERVAL) {
    return res.status(429).json({
      error: "Too many requests. Please wait before tweeting again."
    });
  }

  lastTweetTime = now;


  try {
    const news = await fetchLatestTechNews();
    const tweet = await generateTweetFromNews(news);

if (tweet && news) {
  await postToTwitter(tweet, news.image);   
}
return res.status(204).end(); 
    // if (tweet) {
    //   await postToTwitter(tweet);
    //  return res.status(200).end();
    // //  return res.status(200).send("Tweet posted successfully!");
    // }\
    
    //  res.send("No tweet generated");
  } catch (error) {
   console.error(" Tweet Error:", error.message);
  //  res.status(500).send(" Error generating or posting tweet");
   return res.status(500).end();
  }
});


if (process.env.RUN_LOCAL_CRON === "true") {
  console.log("Cron job active locally: Will run at 8:00 AM daily");

  cron.schedule("0 8 * * *", async () => {
    console.log(" Running local scheduled tweet job...");

    try {
      const news = await fetchLatestTechNews();

      const tweet = await generateTweetFromNews(news);

      
      
      // if (tweet) {
      //   await postToTwitter(tweet);
      //   console.log("Tweet posted via local cron");
      // } 

      if (tweet && news) {
  await postToTwitter(tweet, news.image);   
}else {
        console.log(" No tweet generated by local cron");
      }
    } catch (error) {
      console.error(" Local Cron Error:", error.message);
    }
  });
}

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
