// server.js
import express from "express";
import dotenv from "dotenv";
import cron from "node-cron";
import { fetchLatestTechNews } from "./services/fetchNews.js";
import { generateTweetFromNews } from "./services/generateTweet.js";
import { postToTwitter } from "./services/postToTwitter.js";

dotenv.config();
const app = express();

// ✅ Home Route
app.get("/", (req, res) => {
  res.send("🤖 AI Tweet Bot is running!");
});

// ✅ Tweet Route for Render Cron Job
app.get("/tweet", async (req, res) => {
  try {
    const news = await fetchLatestTechNews();
    console.log("📰 News:", news);

    const tweet = await generateTweetFromNews(news);
    console.log("✍️ Tweet:", tweet);

    if (tweet) {
      await postToTwitter(tweet);
      return res.send("✅ Tweet posted successfully!");
    return res.status(200).send("OK");
    }
     res.send("⚠️ No tweet generated");
     res.status(200).send("No content");
  } catch (error) {
   console.error("❌ Tweet Error:", error.message);
   res.status(500).send("❌ Error generating or posting tweet");
   res.sendStatus(500); 
  }
});

if (process.env.RUN_LOCAL_CRON === "true") {
  console.log("🕗 Cron job active locally: Will run at 8:00 AM daily");

  cron.schedule("0 8 * * *", async () => {
    console.log("⏰ Running local scheduled tweet job...");

    try {
      const news = await fetchLatestTechNews();
      console.log("📰 News:", news);

      const tweet = await generateTweetFromNews(news);
      console.log("✍️ Tweet:", tweet);

      if (tweet) {
        await postToTwitter(tweet);
        console.log("✅ Tweet posted via local cron");
      } else {
        console.log("⚠️ No tweet generated by local cron");
      }
    } catch (error) {
      console.error("❌ Local Cron Error:", error.message);
    }
  });
}

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server running at http://localhost:${PORT}`);
});
